itemlist:
  .byte $01
  .word data3
  .asciiz "THERE ARE SOME KEYS ON THE GROUND HERE."
  .asciiz "KEYS"
  .byte $fe

  .byte $01
  .word data3
  .asciiz "THERE IS A SHINY BRASS LAMP NEARBY."
  .asciiz "LAMP"
  .byte $fe

  .byte $01
  .word data3
  .asciiz "THERE IS FOOD HERE."
  .asciiz "FOOD"
  .byte $fe

  .byte $01
  .word data3
  .asciiz "THERE IS A BOTTLE OF WATER HERE."
  .asciiz "BOTTLE OF WATER"
  .byte $fe

  .byte $ff
